name: slingshot
services:
    php:
        build: ./php/
        volumes:
            - ../../:/var/www/html
        networks:
            - sovereigndb_default

networks:
    sovereigndb_default:
        external: true